development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ice_fire_dev
  pool: 5
  username: root
  password:
  #socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ice_fire_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ice_fire_prod
  pool: 5
  username: root
  password:
